/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const PlutoCustomData = t.iface([], {
  "name": "string",
  "readonly": "string",
  "type": "string",
  "values": t.opt(t.array("DataPair")),
});

const exportedTypeSuite: t.ITypeSuite = {
  PlutoCustomData,
};
export default exportedTypeSuite;
